### ISSUE TITLE
An issue with sphinxdft=3.0.3=*_3 and mkl

### ISSUE THREAD

**Issue by muh-hassani** [conda-forge/sphinxdft-feedstock#34]
When running the latest build with mkl=2021.3.0, I receive the following error:
```
 File "/opt/conda/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 361, in start
    self.convert_notebooks()
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 533, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 498, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 427, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 208, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 147, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 334, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 84, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 105, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ham_spx_chg.run()
------------------

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Input In [17], in <module>
----> 1 ham_spx_chg.run()

File /opt/conda/lib/python3.9/site-packages/pyiron_base/generic/util.py:213, in Deprecator.__deprecate_argument.<locals>.decorated(*args, **kwargs)
    203     if kw in self.arguments:
    204         warnings.warn(
    205             message_format.format(
    206                 "{}.{}({}={})".format(
   (...)
    211             stacklevel=2,
    212         )
--> 213 return function(*args,**kwargs)

File /opt/conda/lib/python3.9/site-packages/pyiron_base/job/generic.py:689, in GenericJob.run(self, delete_existing_job, repair, debug, run_mode, run_again)
    687     self._run_if_repair()
    688 elif status == "initialized":
--> 689     self._run_if_new(debug=debug)
    690 elif status == "created":
    691     self._run_if_created()

File /opt/conda/lib/python3.9/site-packages/pyiron_base/job/generic.py:1392, in GenericJob._run_if_new(self, debug)
   1390 else:
   1391     self.save()
-> 1392     self.run()

File /opt/conda/lib/python3.9/site-packages/pyiron_base/generic/util.py:213, in Deprecator.__deprecate_argument.<locals>.decorated(*args, **kwargs)
    203     if kw in self.arguments:
    204         warnings.warn(
    205             message_format.format(
    206                 "{}.{}({}={})".format(
   (...)
    211             stacklevel=2,
    212         )
--> 213 return function(*args,**kwargs)

File /opt/conda/lib/python3.9/site-packages/pyiron_base/job/generic.py:691, in GenericJob.run(self, delete_existing_job, repair, debug, run_mode, run_again)
    689     self._run_if_new(debug=debug)
    690 elif status == "created":
--> 691     self._run_if_created()
    692 elif status == "submitted":
    693     self._run_if_submitted()

File /opt/conda/lib/python3.9/site-packages/pyiron_base/job/generic.py:1411, in GenericJob._run_if_created(self)
   1409     self.run_if_manually(_manually_print=False)
   1410 elif self.server.run_mode.modal:
-> 1411     self.run_static()
   1412 elif (
   1413     self.server.run_mode.non_modal
   1414     or self.server.run_mode.thread
   1415     or self.server.run_mode.worker
   1416 ):
   1417     self.run_if_non_modal()

File /opt/conda/lib/python3.9/site-packages/pyiron_base/job/generic.py:787, in GenericJob.run_static(self)
    783 self.status.collect = True
    784 self._logger.info(
    785     "{}, status: {}, output: {}".format(self.job_info_str, self.status, out)
    786 )
--> 787 self.run()
    788 if job_crashed:
    789     self.status.aborted = True

File /opt/conda/lib/python3.9/site-packages/pyiron_base/generic/util.py:213, in Deprecator.__deprecate_argument.<locals>.decorated(*args, **kwargs)
    203     if kw in self.arguments:
    204         warnings.warn(
    205             message_format.format(
    206                 "{}.{}({}={})".format(
   (...)
    211             stacklevel=2,
    212         )
--> 213 return function(*args,**kwargs)

File /opt/conda/lib/python3.9/site-packages/pyiron_base/job/generic.py:697, in GenericJob.run(self, delete_existing_job, repair, debug, run_mode, run_again)
    695     self._run_if_running()
    696 elif status == "collect":
--> 697     self._run_if_collect()
    698 elif status == "suspend":
    699     self._run_if_suspended()

File /opt/conda/lib/python3.9/site-packages/pyiron_base/job/generic.py:1495, in GenericJob._run_if_collect(self)
   1489 def _run_if_collect(self):
   1490     """
   1491     Internal helper function the run if collect function is called when the job status is 'collect'. It collects
   1492     the simulation output using the standardized functions collect_output() and collect_logfiles(). Afterwards the
   1493     status is set to 'finished'
   1494     """
-> 1495     self.collect_output()
   1496     self.collect_logfiles()
   1497     if self.job_id is not None:

File /opt/conda/lib/python3.9/site-packages/pyiron_atomistics/sphinx/interactive.py:217, in SphinxInteractive.collect_output(self, force_update, compress_files)
    216 def collect_output(self, force_update=False, compress_files=True):
--> 217     super(SphinxInteractive,self).collect_output(force_update=force_update,compress_files=compress_files)
    218     self._output_interactive_to_generic()

File /opt/conda/lib/python3.9/site-packages/pyiron_atomistics/sphinx/base.py:1376, in SphinxBase.collect_output(self, force_update, compress_files)
   1372 def collect_output(self, force_update=False, compress_files=True):
   1373     """
   1374     Collects the outputs and stores them to the hdf file
   1375     """
-> 1376     self._output_parser.collect(directory=self.working_directory)
   1377     self._output_parser.to_hdf(self._hdf5, force_update=force_update)
   1378     if compress_files:

File /opt/conda/lib/python3.9/site-packages/pyiron_atomistics/sphinx/base.py:2347, in Output.collect(self, directory)
   2340 def collect(self, directory=os.getcwd()):
   2341     """
   2342     The collect function, collects all the output from a SPHInX simulation.
   2343 
   2344     Args:
   2345         directory (str): the directory to collect the output from.
   2346     """
-> 2347     self.collect_sphinx_log(file_name="sphinx.log",cwd=directory)
   2348     self.collect_energy_dat(file_name="energy.dat", cwd=directory)
   2349     self.collect_residue_dat(file_name="residue.dat", cwd=directory)

File /opt/conda/lib/python3.9/site-packages/pyiron_atomistics/sphinx/base.py:2103, in Output.collect_sphinx_log(self, file_name, cwd, check_consistency)
   2101 if not np.any(["Enter Main Loop" in line for line in log_file]):
   2102     self._job.status.aborted = True
-> 2103     raise AssertionError("SPHInX did not enter the main loop; \
   2104         output not collected")
   2105 if not np.any(["Program exited normally." in line
   2106                for line in log_file]):
   2107     self._job.status.aborted = True

AssertionError: SPHInX did not enter the main loop;                     output not collected
AssertionError: SPHInX did not enter the main loop;                     output not collected
```
Removing the pin on mkl, conda complains with the following:
```
Encountered problems while solving:
  - package sphinxdft-3.0.3-h62cddd8_0 requires mkl >=2021.2.0,<2022.0a0, but none of the providers can be installed
```
The conda environment prior to the installation of sphinxdft includes the followings:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aimsgb                    0.1.0              pyhd8ed1ab_1    conda-forge
alembic                   1.7.5              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
anyio                     3.5.0            py39hf3d152e_0    conda-forge
aom                       3.2.0                h9c3ff4c_2    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39h3811e60_1    conda-forge
ase                       3.22.1             pyhd8ed1ab_1    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.0            py39h3811e60_2    conda-forge
black                     21.12b0            pyhd8ed1ab_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0           py39h3811e60_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
certipy                   0.1.3                      py_0    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
cftime                    1.5.1.1          py39hce5d2b2_1    conda-forge
charset-normalizer        2.0.10             pyhd8ed1ab_0    conda-forge
click                     8.0.3            py39hf3d152e_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.11.0           py39hf3d152e_0    conda-forge
conda-package-handling    1.7.3            py39h3811e60_1    conda-forge
configurable-http-proxy   4.5.0           node17_h7e777a6_2    conda-forge
cryptography              36.0.1           py39h95dcef6_0    conda-forge
curl                      7.81.0               h2574ce0_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.26          py39he80948d_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.5.1            py39he80948d_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
double-conversion         3.1.7                h9c3ff4c_0    conda-forge
eigen                     3.4.0                h4bd325d_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
executing                 0.8.2              pyhd8ed1ab_0    conda-forge
expat                     2.4.3                h9c3ff4c_0    conda-forge
f90wrap                   0.2.7            py39h984b4d8_1    conda-forge
ffmpeg                    4.4.1                h6987444_0    conda-forge
fftw                      3.3.10          nompi_h77c792f_102    conda-forge
flask                     2.0.2              pyhd8ed1ab_0    conda-forge
flit-core                 3.6.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.28.5           py39h3811e60_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py39hf3d152e_4    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
git                       2.34.1          pl5321hc30692c_0    conda-forge
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.26             pyhd8ed1ab_0    conda-forge
gl2ps                     1.4.2                h0708190_0    conda-forge
glew                      2.1.0                h9c3ff4c_2    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2            py39h78fa15d_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
greenlet                  1.1.2            py39he80948d_1    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gst-plugins-base          1.18.5               hf529b03_3    conda-forge
gstreamer                 1.18.5               h9f60fe5_3    conda-forge
h5io                      0.1.7              pyh8a188c0_0    conda-forge
h5py                      3.6.0           nompi_py39h7e08c79_100    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h2750804_103    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.10.1           py39hf3d152e_0    conda-forge
importlib_metadata        4.10.1               hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
iprpy-data                2021.2.23          pyh44b312d_0    conda-forge
ipykernel                 6.7.0            py39hef51801_0    conda-forge
ipython                   8.0.1            py39hf3d152e_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge
itsdangerous              2.0.1              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1           py39hf3d152e_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsoncpp                   1.9.4                h4bd325d_3    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.1.1              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py39hf3d152e_1    conda-forge
jupyter_server            1.13.3             pyhd8ed1ab_0    conda-forge
jupyter_telemetry         0.1.0              pyhd8ed1ab_1    conda-forge
jupyterhub                2.0.2                hd8ed1ab_0    conda-forge
jupyterhub-base           2.0.2              pyhd8ed1ab_0    conda-forge
jupyterlab                3.2.8              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.10.3             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
kim-api                   2.2.1                h5c8ed42_0    conda-forge
kiwisolver                1.3.2            py39h1a9c180_1    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
lammps                    2021.09.29      py39hc0ae7ba_openmpi_2    conda-forge
latexcodec                2.0.1              pyh9f0ad1d_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libarchive                3.5.2                hccf745f_1    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libclang                  13.0.0          default_hc23dcda_0    conda-forge
libcurl                   7.81.0               h2574ce0_0    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libdrm                    2.4.109              h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libglib                   2.70.2               h174f98d_1    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn2                   2.3.2                h7f98852_0    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libllvm13                 13.0.0               hf817b99_0    conda-forge
libmamba                  0.19.1               h3985d26_0    conda-forge
libmambapy                0.19.1           py39h8bfa403_0    conda-forge
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
libnghttp2                1.43.0               h812cca2_1    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpciaccess              0.16                 h516909a_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     14.1                 hd57d9b9_1    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsolv                   0.7.19               h780b84a_5    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtheora                 1.1.1             h7f98852_1005    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.42.0               h7f98852_0    conda-forge
libva                     2.13.0               h7f98852_2    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libvpx                    1.11.0               h9c3ff4c_3    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzip                    1.8.0                h4de3113_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
loguru                    0.5.3            py39hf3d152e_3    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mako                      1.1.6              pyhd8ed1ab_0    conda-forge
mamba                     0.19.1           py39hfa8f2c8_0    conda-forge
markupsafe                2.0.1            py39h3811e60_1    conda-forge
matplotlib-base           3.5.1            py39h2fa2bec_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mendeleev                 0.9.0              pyh8a188c0_0    conda-forge
mistune                   0.8.4           py39h3811e60_1005    conda-forge
mlip                      1.0                  hf1f3868_2    conda-forge
mock                      4.0.3            py39hf3d152e_2    conda-forge
monty                     2022.1.19          pyhd8ed1ab_0    conda-forge
mpc                       1.2.1                h9f54685_0    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           0.4.3            py39hf3d152e_4    conda-forge
mysql-common              8.0.28               ha770c72_0    conda-forge
mysql-libs                8.0.28               hfa10184_0    conda-forge
n2p2                      2.1.4            py39hb3238b3_2    conda-forge
nbclassic                 0.3.5              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.10             pyhd8ed1ab_1    conda-forge
nbconvert                 6.4.0            py39hf3d152e_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.8           nompi_py39h64b754b_101    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
nglview                   3.0.3              pyh8a188c0_0    conda-forge
nodejs                    17.1.0               h8ca31f7_2    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
notebook                  6.4.7              pyha770c72_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.74                 hb5efdd6_0    conda-forge
numexpr                   2.8.0           py39hbd72853_100    conda-forge
numpy                     1.22.0           py39h91f2184_1    conda-forge
oauthlib                  3.1.1              pyhd8ed1ab_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openkim-models            2021.01.28           h2cc385e_1    conda-forge
openmpi                   4.1.2                hbfc84c5_0    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
palettable                3.3.0                      py_0    conda-forge
pamela                    1.0.0                      py_0    conda-forge
pandas                    1.3.5            py39hde0f152_0    conda-forge
pandoc                    2.17.0.1             h7f98852_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  2.9.2              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathlib2                  2.3.6            py39hf3d152e_1    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                h032f7d1_0    conda-forge
perl                      5.32.1          1_h7f98852_perl5    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
phonopy                   2.12.0           py39hce5d2b2_1    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py39ha612740_0    conda-forge
pint                      0.18               pyhd8ed1ab_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pkg-config                0.29.2            h36c2ea0_1008    conda-forge
platformdirs              2.3.0              pyhd8ed1ab_0    conda-forge
plotly                    5.5.0              pyhd8ed1ab_0    conda-forge
proj                      8.2.0                h277dcde_0    conda-forge
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
psutil                    5.9.0            py39h3811e60_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pugixml                   1.11.4               h9c3ff4c_0    conda-forge
pure_eval                 0.2.1              pyhd8ed1ab_1    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pybtex                    0.24.0             pyhd8ed1ab_2    conda-forge
pycosat                   0.6.3           py39h3811e60_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycurl                    7.44.1           py39h72e3413_1    conda-forge
pyfiglet                  0.8.post1                  py_0    conda-forge
pyfileindex               0.0.6              pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyiron                    0.4.6              pyhd8ed1ab_0    conda-forge
pyiron-data               0.0.17               hd8ed1ab_0    conda-forge
pyiron_atomistics         0.2.35             pyhd8ed1ab_2    conda-forge
pyiron_base               0.5.1              pyhd8ed1ab_1    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pymatgen                  2022.1.20        py39h1a9c180_0    conda-forge
pynacl                    1.5.0            py39h3811e60_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1           py39h3811e60_0    conda-forge
pyscal                    2.10.15          py39h5472131_1    conda-forge
pysocks                   1.7.1            py39hf3d152e_4    conda-forge
pysqa                     0.0.15             pyhd8ed1ab_0    conda-forge
pytables                  3.6.1            py39h2669a42_5    conda-forge
python                    3.9.7           hb7a2778_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.1              pyh9f0ad1d_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h3811e60_3    conda-forge
pyzmq                     22.3.0           py39h37b5a0c_1    conda-forge
qt                        5.12.9               ha98a1a1_5    conda-forge
quippy                    0.0.1            py39hbb6cefa_4    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.19          py39h3811e60_0    conda-forge
ruamel.yaml.clib          0.2.6            py39h3811e60_0    conda-forge
ruamel_yaml               0.15.80         py39h3811e60_1006    conda-forge
scandir                   1.10.0           py39h3811e60_4    conda-forge
scikit-learn              1.0.2            py39h4dfa638_0    conda-forge
scipy                     1.7.3            py39hee8e79c_0    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
seekpath                  2.0.1              pyh44b312d_1    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                59.8.0           py39hf3d152e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
sniffio                   1.2.0            py39hf3d152e_2    conda-forge
spglib                    1.16.3           py39hce5d2b2_0    conda-forge
sphinxdft-data            0.0.1                hd8ed1ab_2    conda-forge
sqlalchemy                1.4.30           py39h3811e60_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
stack_data                0.1.4              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.1           py39hce5d2b2_0    conda-forge
svt-av1                   0.8.7                h9c3ff4c_1    conda-forge
sympy                     1.9              py39hf3d152e_1    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tbb                       2021.5.0             h4bd325d_0    conda-forge
tbb-devel                 2021.5.0             h4bd325d_0    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
terminado                 0.12.1           py39hf3d152e_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tomli                     1.2.2              pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39h3811e60_2    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.1            py39h3811e60_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
uncertainties             3.1.6              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
utfcpp                    3.2.1                ha770c72_0    conda-forge
vtk                       9.1.0           qt_py39h6e664cc_203    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.2.3              pyhd8ed1ab_0    conda-forge
werkzeug                  2.0.2              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha56f1ee_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.5.2            py39hf3d152e_1    conda-forge
x264                      1!161.3030           h7f98852_1    conda-forge
x265                      3.5                  h4bd325d_1    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.6.3                he1b5a44_4    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.1                ha95c52a_0    conda-forge
```

**Comment by freyso** [comment]
I tried to provide a fix for the issue by pull request #35, something I pointed out already in october: this might be a problem of inconsistent CPU hardware, so I fix the hardware architecture to an old common ancestor (x64-64 sse2).

**Comment by jan-janssen** [comment]
It seems like the new Sphinx version `_4` is working fine - at least on my tests on my binder. I currently run the pyiron tests again https://github.com/pyiron/pyiron_atomistics/pull/511

**Comment by muh-hassani** [comment]
The docker build works with `mkl=2021.3.0`. Thanks, @freyso, for the new build.

**Comment by muh-hassani** [comment]
@jan-janssen, the new pull request from @jan-janssen also shows with the latest mkl, the docker build is completed.
